manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: refil
      url-base: https://github.com/refil
    - name: mine
      url-base: https://github.com/pijanowskim
  projects:
    - name: zmk
      remote: mine
      revision: adv360-z3.2-2-edited
      import: app/west.yml
  self:
    path: config
